CREATE TABLE position (
   id bigint generated by default as identity,
   name VARCHAR(50),
   primary key (id)
);

INSERT INTO position (id, name) VALUES (1, 'Assistant');
INSERT INTO position (id, name) VALUES (2, 'Architect');

CREATE TABLE person (
   id bigint generated by default as identity,
   name VARCHAR(255),
   last_name VARCHAR(255),
   address VARCHAR(255),
   cellphone VARCHAR(255),
   city_name VARCHAR(255),
   primary key (id)
);

INSERT INTO person (id, name, last_name, address, cellphone, city_name) VALUES (1, 'Armando', 'Contreras', 'Edificio Luz', '3005248855', 'Medellín');
INSERT INTO person (id, name, last_name, address, cellphone, city_name) VALUES (2, 'Jessica', 'Gomez', 'calle 3 4-55', '3005248899', 'Pasto');

CREATE TABLE employee (
   id bigint generated by default as identity,
   salary bigint,
   person_id bigint,
   position_id bigint,
   primary key (id)
);
alter table employee add constraint person_fk foreign key (person_id) references person;
alter table employee add constraint position_fk foreign key (position_id) references position(id);

INSERT INTO employee (id, salary, person_id, position_id) VALUES (1, 540, 1, 1);
INSERT INTO employee (id, salary, person_id, position_id) VALUES (2, 440, 2, 1);